version: '3'
services:

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /usr/src/app
    tty: true
    volumes:
      - .:/usr/src/app
    environment:
      HOST: 0.0.0.0 
      PORT: 8080
      MONGO_URI: "mongodb://mongo:27017/dms3"
      AMQP_URI: "amqp://rabbit:5672"
    ports:
      - '7070:8080'
    depends_on:
      - 'rabbit'
    networks:
      - app_network

  mongo:
    image: mongo:4.2
    ports:
      - '28018:27017'
    networks:
      - app_network

  rabbit:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
