enum SyncType {
  ALL_USERS_SYNC = 'ALL_USERS_SYNC',
  MULTIPLE_USERS_SYNC = 'MULTIPLE_USERS_SYNC',
  SINGLE_USER_SYNC = 'SINGLE_USER_SYNC',
  ALL_DEPARTMENTS_SYNC = 'ALL_DEPARTMENTS_SYNC',
  MULTIPLE_DEPARTMENTS_SYNC = 'MULTIPLE_DEPARTMENTS_SYNC',
  SINGLE_DEPARTMENT_SYNC = 'SINGLE_DEPARTMENT_SYNC'
}

export default SyncType;
